name: Run Mysql Example
on: push

jobs:
  mysql-schema-initialization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: |
          mysql -uroot -h127.0.0.1 -e 'SELECT version();';
          mysql -uroot -h127.0.0.1 < .github/setups/schema.sql;
          mysql -uroot -h127.0.0.1 -e 'use customer; Show tables;';





