name: Run Mysql Example
on: push
env:
  password: 'password'

jobs:
  mysql-schema-initialization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          auto-start: true
          user: sql
          root-password: password

      - run: |
          mysql -uroot -p$password -h127.0.0.1 -e 'SELECT version();';
          mysql -uroot -p$password -h127.0.0.1 < .github/setups/schema.sql;
          mysql -uroot -p$password -h127.0.0.1 -e MYSQL_DATABASE=customer -e 'Show tables;';





