name: Run Mysql Example
on: push
env:
  password: '1234'

jobs:
  mysql-schema-initialization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          auto-start: true
          user: sql
          password: 1234

      - run: |
          mysql -usql -p$password -h127.0.0.1 -e 'SELECT version();';
          mysql -usql -p$password -h127.0.0.1 < .github/setups/schema.sql;
          mysql -usql -p$password -h127.0.0.1 -e 'use customer; Show tables;';





